[package]
name = "zk-odst"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "blake2f"
path = "./src/blake2f"

[dependencies]
halo2_proofs = "0.1.0"
